all: direct_mapped_cache_lru.o direct_mapped_cache.o
direct_mapped_cache_lru.o: direct_mapped_cache_lru.cpp
	g++ -std=c++17 direct_mapped_cache_lru.cpp -o direct_mapped_cache_lru.out
direct_mapped_cache.o: direct_mapped_cache.cpp
	g++ -std=c++17 direct_mapped_cache.cpp -o direct_mapped_cache.out